### ISSUE TITLE
graphQL

### ISSUE THREAD

**Issue by silentrain23** [Savjee/home-energy-monitor#85]
Hallo and thank you for your nice project! Very well done.

A question: I would like to make some calls to the graphQL using [tray.io](https://tray.io/docs/api/sandbox) but, every time I try to call the endpoint It doesnt work with an error
"message": "Syntax Error: Expected Name, found String \"query\"",
            "locations": [
            
        My question is: is the graphql.js a complete server? Shouldnt it be available on port 9000? Does it lack of introspection query to fetch the field names?
        
        Thank you for supporting ms

**Comment by Savjee** [comment]
I'm not familiar with tray.io, so I can't help you with that.
Graphql.js itself doesn't contain a server. Here's where I "connect" it to the Lambda function:
https://github.com/Savjee/home-energy-monitor/blob/70fd234b305f2d3f8040fb9a9ef743cf9b9b6e74/src-aws/functions/graphql/graphql.js#L45

It's possible that tray.io sends the query in a different format than expected. Could you show me what data it POST's to the server?

(I'm also closing this issue, because it's not related to the project itself but rather an implementation. You can still reply though)

**Comment by silentrain23** [comment]
Hello Saviee

Yes, I know the function.

My question is: is garphql.js a sort of API or a simplified version of GraphQL?
Do you think that by installing a GRAPHQL server I can easily access to the data stored in in DYNAMODB?

thank u


Emanuele

**Comment by Savjee** [comment]
Graphql.js is a reference implementation for GraphQL. It's not a simplified version, and it has everything needed to process queries. However, it is not capable of serving HTTP requests by itself. That's why I wrapped it in a function that is called by API Gateway.

> Do you think that by installing a GRAPHQL server I can easily access to the data stored in in DYNAMODB?

Why would you need to install a dedicated server? The Lambda function takes that role and I already wrote resolvers to grab data from DynamoDB. I'm not sure what you're trying to accomplish.
